import type { Alliance, NationDef } from "./types";

export const NATIONS: NationDef[] = [
  {
    id: "us",
    name: "United States",
    short: "US",
    alliance: "nato",
    subtitle: "USAREUR · V & VII Corps",
    headerInk: "light",
  },
  {
    id: "baor",
    name: "British Army of the Rhine",
    short: "BAOR",
    alliance: "nato",
    subtitle: "I (BR) Corps",
    headerInk: "light",
  },
  {
    id: "west-germany",
    name: "West Germany",
    short: "FRG",
    alliance: "nato",
    subtitle: "Bundeswehr · I, II, III Korps",
    headerInk: "light",
  },
  {
    id: "france",
    name: "France",
    short: "FRA",
    alliance: "nato",
    subtitle: "Forces Françaises en Allemagne",
    headerInk: "light",
  },
  {
    id: "canada",
    name: "Canada",
    short: "CAN",
    alliance: "nato",
    subtitle: "4 CMBG",
    headerInk: "light",
  },
  {
    id: "netherlands",
    name: "Netherlands",
    short: "NLD",
    alliance: "nato",
    subtitle: "I (NL) Corps",
    headerInk: "light",
  },
  {
    id: "belgium",
    name: "Belgium",
    short: "BEL",
    alliance: "nato",
    subtitle: "I (BE) Corps",
    headerInk: "light",
  },
  {
    id: "denmark",
    name: "Denmark",
    short: "DNK",
    alliance: "nato",
    subtitle: "Jutland Division",
    headerInk: "light",
  },
  {
    id: "italy",
    name: "Italy",
    short: "ITA",
    alliance: "nato",
    subtitle: "5th Army Corps",
    headerInk: "light",
  },
  {
    id: "norway",
    name: "Norway",
    short: "NOR",
    alliance: "nato",
    subtitle: "Brigade Nord",
    headerInk: "light",
  },
  {
    id: "soviets",
    name: "Soviet Union",
    short: "USSR",
    alliance: "warpac",
    subtitle: "GSFG · Northern Group of Forces",
    headerInk: "light",
  },
  {
    id: "east-germany",
    name: "East Germany",
    short: "GDR",
    alliance: "warpac",
    subtitle: "Nationale Volksarmee",
    headerInk: "light",
  },
  {
    id: "poland",
    name: "Poland",
    short: "POL",
    alliance: "warpac",
    subtitle: "Ludowe Wojsko Polskie",
    headerInk: "dark",
  },
  {
    id: "czechoslovakia",
    name: "Czechoslovakia",
    short: "TCH",
    alliance: "warpac",
    subtitle: "ČSLA",
    headerInk: "light",
  },
  {
    id: "hungary",
    name: "Hungary",
    short: "HUN",
    alliance: "warpac",
    subtitle: "Magyar Néphadsereg",
    headerInk: "light",
  },
  {
    id: "romania",
    name: "Romania",
    short: "ROU",
    alliance: "warpac",
    subtitle: "Armata Populară Română",
    headerInk: "light",
  },
  {
    id: "bulgaria",
    name: "Bulgaria",
    short: "BGR",
    alliance: "warpac",
    subtitle: "Bălgarska Narodna Armija",
    headerInk: "light",
  },
  {
    id: "japan",
    name: "Japan",
    short: "JPN",
    alliance: "other",
    subtitle: "JGSDF aviation",
    headerInk: "light",
  },
  {
    id: "south-africa",
    name: "South Africa",
    short: "RSA",
    alliance: "other",
    subtitle: "SANDF aviation",
    headerInk: "light",
  },
  {
    id: "zapadoslavia",
    name: "Zapadoslavia",
    short: "ZAP",
    alliance: "warpac-alt",
    subtitle: "Armed Forces of Zapadoslavia",
    headerInk: "light",
  },
  {
    id: "yugoslavia",
    name: "Yugoslavia",
    short: "YUG",
    alliance: "warpac-alt",
    subtitle: "Yugoslav People's Army",
    headerInk: "light",
  },
];

export const NATION_BY_ID: Record<string, NationDef> = Object.fromEntries(
  NATIONS.map((n) => [n.id, n]),
);

export function nationsByAlliance(alliance: Alliance): NationDef[] {
  return NATIONS.filter((n) => n.alliance === alliance);
}
